### ISSUE TITLE
MySQL 一节中，是否考虑使用 utf8mb4 作为例子

### ISSUE THREAD

**Issue by skyline75489** [liheyuan/hands-on-microservices#2]
https://github.com/liheyuan/hands-on-microservices/blob/master/ms-storage/mysql-devops.md

utf8mb4 对于 emoji 的支持更好。

**Comment by liheyuan** [comment]
是的，改一下。

**Comment by liheyuan** [comment]
https://github.com/liheyuan/hands-on-microservices/commit/7c764e54e3851ab6a8f83244bab516a185c1acb8 @skyline75489
